services:
  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_DB: tp3_test1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"  # <- FIXED

  app:
    image: demo
    container_name: springboot-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tp3_test1
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8000:8000"